// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe21KffonZLAHdKZRUPfw2BxcJBM3bSrw',
    appId: '1:696485219778:web:d32096aeb62d5674315a5b',
    messagingSenderId: '696485219778',
    projectId: 'arkroot-todo-app',
    authDomain: 'arkroot-todo-app.firebaseapp.com',
    storageBucket: 'arkroot-todo-app.firebasestorage.app',
    measurementId: 'G-T4ZCRR8514',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80QP_WfCYmWGe_n9VS2YpZhhFV6q7zA0',
    appId: '1:696485219778:android:4c816b2b4da44d3d315a5b',
    messagingSenderId: '696485219778',
    projectId: 'arkroot-todo-app',
    storageBucket: 'arkroot-todo-app.firebasestorage.app',
  );

}